### ISSUE TITLE
Getting an Error when using reformat.

### ISSUE THREAD

**Issue by MohammedZaytoonIQ** [emit-sds/emit-utils#12]
After installing emit-sds main fully when trying to run the code as following 
`py reformat.py 1.nc output`
I'm getting the following error:
`Traceback (most recent call last):
  File "C:\Users\moham\Desktop\emit-main\emit-utils\emit_utils\reformat.py", line 7, in <module>
    import netCDF4
  File "C:\Users\moham\AppData\Local\Programs\Python\Python312\Lib\site-packages\netCDF4\__init__.py", line 17, in <module>
    from ._netCDF4 import *
  File "src\\netCDF4\\_netCDF4.pyx", line 1, in init netCDF4._netCDF4
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

What is the problem? is there anything I didn't install or missed that caused this problem to happen?

**Comment by MohammedZaytoonIQ** [comment]
I used `python reformat.py input.nc output` it worked but I didn't get the expected data format, instead I got multiple different files which are not in ENV format.
![image](https://github.com/emit-sds/emit-utils/assets/146940171/701af2aa-cac2-4135-b66e-8db157602581)

**Comment by kiranjmiirs** [comment]
How to generate GLT files
